Updates for XVF3615 interactions
xmos/avs-device-sdk pull request #72
Opened 2022-04-11 20:00 UTC by lucianomartin

* add support for KWD using HID event. This will be an alternative to using the Sensory KWD with UA device.
    * add mechanism to retrieve WW indexes for HID and GPIO KWD's

2022-04-12 16:34 UTC, mbanth requested changes
Why do the include paths have directories with the same name at different levels of the hierarchy, e.g., `GPIO/include/GPIO`?

2022-04-13 09:51 UTC, lucianomartin commented on KWD/HID/src/HIDKeywordDetector.cpp
> +// Copyright (c) 2021 XMOS LIMITED. This Software is subject to the terms of the
> Why do the include paths have directories with the same name at different levels of the hierarchy, e.g., `GPIO/include/GPIO`?

We followed the style of the other AVS device SDK folders, such as https://github.com/xmos/avs-device-sdk/tree/master/KWD/Sensory/include/Sensory

2022-04-13 09:59 UTC, lucianomartin commented on KWD/HID/src/HIDKeywordDetector.cpp
> +// Copyright (c) 2021 XMOS LIMITED. This Software is subject to the terms of the
These suggestions are valid and they could be implemented in the future. I don't have much time before my holiday so I would create an issue and address them when I am back.

2022-04-13 10:04 UTC, lucianomartin commented on KWD/GPIO/src/GPIOKeywordDetector.cpp
> +            auto begin_server_index = current_index - (current_device_index - begin_device_index);
The second issue in this comment is already addressed in the code of the AVS device SDK:
https://github.com/xmos/avs-device-sdk/blob/master/SampleApp/src/KeywordObserver.cpp#L75
No change is required in the code of this PR.

2022-04-13 10:36 UTC, lucianomartin commented on KWD/GPIO/src/GPIOKeywordDetector.cpp
> +uint64_t readIndex(uint8_t* payload, int start_index) {
I updated this code, but I doubt it is more efficient than the first implementation as a byte swap is needed after the memcpy.

2022-04-13 12:41 UTC, lucianomartin commented on KWD/GPIO/src/GPIOKeywordDetector.cpp
> +            int rc = 0;
I will create an issue about this topic

2022-04-13 12:56 UTC, lucianomartin commented on KWD/GPIO/src/GPIOKeywordDetector.cpp
> +            int rc = 0;
See https://github.com/xmos/avs-device-sdk/issues/73

2022-04-13 12:56 UTC, lucianomartin commented on KWD/HID/src/HIDKeywordDetector.cpp
> +// Copyright (c) 2021 XMOS LIMITED. This Software is subject to the terms of the
See https://github.com/xmos/avs-device-sdk/issues/73

2022-04-13 12:59 UTC, mbanth commented on KWD/GPIO/src/GPIOKeywordDetector.cpp
> +            uint64_t beginWWDeviceIndex = readIndex(payload, 9);
You seem to have reverted to using `WW` instead of `KW` when renaming these variables.

2022-04-13 12:59 UTC, mbanth commented on KWD/HID/src/HIDKeywordDetector.cpp
> +            uint64_t beginWWDeviceIndex = readIndex(payload, 9);
You seem to have reverted to using `WW` instead of `KW` when renaming these variables.

2022-04-13 12:59 UTC, mbanth commented on KWD/HID/src/HIDKeywordDetector.cpp
> +// Copyright (c) 2021 XMOS LIMITED. This Software is subject to the terms of the
I'm happy for the possibility of refactoring to be recorded in a new issue.

2022-04-13 13:00 UTC, mbanth requested changes
Two instances where renaming does not seem to follow a stated pattern.

2022-04-13 13:27 UTC, mbanth approved these changes
All good now.

2022-04-13 16:10 UTC, merged